#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap           8
bspc config active_border_color  \#ffffff
bspc config focused_border_color \#ffffff
bspc config normal_border_color  \#222328

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Pictures/beach-blue-dawn.jpg
