#! /bin/sh

xset s off  #Disable screen saver blanking
xset -dpms  # Turn off DPMS
xsetroot -cursor_name left_ptr &
xinput set-prop "VEN_04F3:00 04F3:311C Touchpad" 375 1

if [[ $(xrandr --query | grep '^DP-1') = *" connected "* ]]; then
    bspc monitor "DP-1" -d 1 2 3 4 5
    bspc monitor "DP-1" -d 6
    export EXTERNAL_DPI_MODE=3840x1600
    xrandr --output eDP-1 --pos 0x2400 --output DP-1 --mode 3840x1600 --pos 0x0
elif [[ $(xrandr --query | grep '^DP-2') = *" connected "* ]]; then
    bspc monitor "DP-2" -d 1 2 3 4 5
    export EXTERNAL_DPI_MODE=3840x1600
    xrandr --output eDP-1 --mode 1920x1080 --pos 0x1600 --output DP-2 --mode 3840x1600 --pos 0x0
elif [[ $(xrandr --query | grep '^DP-3') = *" connected "* ]]; then
    bspc monitor "DP-3" -s "eDP-1"
    bspc monitor "DP-3" -d 1 2 3 4 5
    export EXTERNAL_DPI_MODE=3840x1600
    xrandr --output eDP-1 --mode 3840x2400 --pos 0x2400 --output DP-3 --mode 3840x2160 --pos 0x0
else
    bspc monitor "eDP-1" -d 1 2 3 4 5 6
fi

feh --bg-center ~/Pictures/pexels-francesco-ungaro-2325446.jpg

polybar --config=~/.config/polybar/config.ini main -r &
comp &

bspc config border_width         4
bspc config window_gap           8
bspc config active_border_color  \#ffffff
bspc config focused_border_color \#ffffff
bspc config normal_border_color  \#2f343f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
sxhkd &
